spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food-shop
    username: "${DB_USERNAME:Postgres}"
    password: "${DB_PASSWORD:any_local_pwd}"
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: "optional:file:.env[.properties]"

api:
  security:
    token:
      secret: ${JWT_SECRET:super-secret-key-temporary-for-development-only}